Airport.create(code: 'NYC', city: 'New York City')
Airport.create(code: 'SFO', city: 'San Francisco')
Airport.create(code: 'AUS', city: 'Austin')
Airport.create(code: 'CHI', city: 'Chicago')
Airport.create(code: 'PHI', city: 'Philadelphia')
